---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-demo-deployment
  template:
    metadata:
      labels:
        app: cache-demo-deployment
    spec:
      containers:
      - name: cache-demo-application
        image: venkateshpakanati/cache-demo
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cache-demo-service
spec:
  type: NodePort
  selector:
    app: cache-demo-deployment 
  ports:
   - nodePort: 30161
     port: 8080
     targetPort: 8080
     protocol: TCP 