{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "projectchart.serviceAccountName" . }}
  labels:
{{ include "projectchart.labels" . | indent 4 }}
{{- end -}}
